### ISSUE TITLE
Kernel Panic "Exception was unhandled" tcpip_adapter_set_hostname

### ISSUE THREAD

**Issue by tripflex** [tripflex/provision-wifi#6]
Error:
```shell
[Jun  1 12:43:32.300] Guru Meditation Error: Core  0 panic'ed (LoadProhibited)
[Jun  1 12:43:32.302] . Exception was unhandled.
```

Core Dump:
```shell
#1  0x401b3d9e in tcpip_adapter_set_hostname (tcpip_if=TCPIP_ADAPTER_IF_STA,
Unmapped addr 0x1
    hostname=0x1 "")
    at /opt/Espressif/esp-idf/components/tcpip_adapter/tcpip_adapter_lwip.c:1137
#2  0x401b3df0 in tcpip_adapter_set_hostname_api (msg=0x3ffd9ac0)
```

**Comment by tripflex** [comment]
OMG what a waste of 4+ hours ... was because the `provision.wifi.sta.enable` was set at bottom of yaml file, fixed in f551717f7e06b9993b758e6a75f817f9588667f7
